-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSfoFdDTNc19qpfSk
bzRhPdm9BoZckVZJZ8kprVhT9w+gCgYIKoZIzj0DAQehRANCAARc0MZp6BjdaoY3
N+i55onWxWSxiiaLYeiREa03ALztCokf4z0YN2bPc1w0j3shVQNLzASk9HuorKqB
1oQwWxxw
-----END PRIVATE KEY-----